function company(){
  $('#app').innerHTML=`<section class="sec white"><div class="w"><h2>LIST YOUR COMPANY</h2><p class="lead">Licensed taxi, limo and private transportation operators only. You choose your vehicle, your price, and the nights you want to work. Red Rocks DD defines the service.</p><div class="form"><div class="fg"><div class="f"><label>Company</label><input id="cc"></div><div class="f"><label>Driver name</label><input id="cn"></div><div class="f"><label>Email</label><input id="ce"></div><div class="f"><label>Password</label><input type="password" id="cp"></div><div class="f"><label>Phone</label><input id="ct"></div><div class="f"><label>License / authority #</label><input id="cl"></div><div class="f"><label>Insurance carrier</label><input id="ci"></div><div class="f"><label>Your transportation price</label><input type="number" id="cpr" placeholder="250"></div><div class="f"><label>Vehicle</label><input id="cv" placeholder="Chevrolet Suburban"></div><div class="f"><label>Year & color</label><input id="cy"></div><div class="f"><label>Capacity</label><input type="number" id="cap"></div></div><div class="note"><b>Required service:</b> pickup 4:30 PM or later, round trip, chairs, cooler, ice, Bluetooth speaker, driver remains at Red Rocks, up to 8 hours.</div><div class="f"><label>Driver photo</label><input type="file" accept="image/*" id="dp"></div><div class="f"><label>Vehicle photo</label><input type="file" accept="image/*" id="vp"></div><div class="f"><label>Dates you want to work</label><div class="cal">${days(45).map(x=>`<label class="day"><input type="checkbox" class="cd" value="${x.v}"> ${x.l}</label>`)}</div></div><label class="consent"><input type="checkbox" id="agree"> I confirm I operate licensed commercial passenger transportation, carry required insurance, and agree to the standard Red Rocks DD service and <a href="#/terms" target="_blank">Terms</a>.</label><div id="cm"></div><br><button class="btn red" onclick="signup()">Create Account & Submit</button></div></div></section>`
}
function file(f){return new Promise((r,j)=>{if(!f)return r('');if(f.size>1500000)return j(Error('Use an image under 1.5 MB'));let x=new FileReader;x.onload=()=>r(x.result);x.onerror=j;x.readAsDataURL(f)})}
async function signup(){
  if(!$('#agree').checked)return msg('#cm','Confirm the operator requirements.','bad');
  const D=$$('.cd:checked').map(x=>x.value);if(!D.length)return msg('#cm','Choose at least one date.','bad');
  let P;try{P={company_name:$('#cc').value.trim(),driver_name:$('#cn').value.trim(),email:$('#ce').value.trim(),phone:$('#ct').value.trim(),license_number:$('#cl').value.trim(),insurance_carrier:$('#ci').value.trim()||null,price_cents:+$('#cpr').value*100,vehicle:{make_model:$('#cv').value.trim(),year_color:$('#cy').value.trim(),capacity:+$('#cap').value,driver_photo_url:await file($('#dp').files[0]),vehicle_photo_url:await file($('#vp').files[0])},dates:D}}catch(e){return msg('#cm',e.message,'bad')}
  if(!P.company_name||!P.driver_name||!P.email||!P.phone||!P.license_number||!P.price_cents||!P.vehicle.make_model||!P.vehicle.capacity)return msg('#cm','Complete the required fields.','bad');
  localStorage.setItem('rrdd_pending',JSON.stringify(P));
  const z=await sb.auth.signUp({email:P.email,password:$('#cp').value,options:{emailRedirectTo:location.origin+'/#/login'}});
  if(z.error)return msg('#cm',z.error.message,'bad');
  if(z.data.session){await finish(z.data.user.id);location.hash='#/dashboard'}else msg('#cm','Check your email to verify the account, then log in. Your application will finish automatically.','good')
}
async function finish(uid){
  const q=localStorage.getItem('rrdd_pending')||localStorage.getItem('cs_pending');if(!q)return;
  const P=JSON.parse(q);let r=await sb.from('caddy_operators').insert({user_id:uid,company_name:P.company_name,driver_name:P.driver_name,email:P.email,phone:P.phone,license_number:P.license_number,insurance_carrier:P.insurance_carrier,price_cents:P.price_cents}).select().single(),o=r.data;
  if(r.error)o=(await sb.from('caddy_operators').select('*').eq('user_id',uid).maybeSingle()).data;
  if(!o)throw Error('Unable to attach operator profile.');
  const vv=await sb.from('caddy_vehicles').select('id').eq('operator_id',o.id);if(!vv.data?.length)await sb.from('caddy_vehicles').insert({operator_id:o.id,...P.vehicle});
  for(const d of P.dates)await sb.from('caddy_availability').upsert({operator_id:o.id,service_date:d,available:true},{onConflict:'operator_id,service_date'});
  localStorage.removeItem('rrdd_pending');localStorage.removeItem('cs_pending')
}
function login(){$('#app').innerHTML=`<section class="sec white"><div class="w"><div class="form" style="max-width:440px;margin:auto"><h2>DRIVER LOGIN</h2><div class="f"><label>Email</label><input id="le"></div><div class="f"><label>Password</label><input type="password" id="lp"></div><div id="lm"></div><button class="btn dark" onclick="signin()">Log In</button></div></div></section>`}
async function signin(){const z=await sb.auth.signInWithPassword({email:$('#le').value.trim(),password:$('#lp').value});if(z.error)return msg('#lm',z.error.message,'bad');await finish(z.data.user.id);location.hash='#/dashboard'}
async function dashboard(){
  if(!await sess())return location.hash='#/login';const o=await opme();if(!o)return $('#app').innerHTML='<section class="sec"><div class="w"><div class="note">Login works, but no Red Rocks DD operator profile is attached yet.</div></div></section>';
  const v=(await sb.from('caddy_vehicles').select('*').eq('operator_id',o.id).eq('active',true).maybeSingle()).data,a=(await sb.from('caddy_availability').select('*').eq('operator_id',o.id)).data||[],r=(await sb.from('caddy_requests').select('*').eq('operator_id',o.id).order('service_date')).data||[];window.D={o,v,a,r};
  $('#app').innerHTML=`<section class="sec white"><div class="w"><div class="row"><div><h2>${esc(o.company_name)}</h2><span class="muted">${o.approved?'Approved & live':'Pending approval'} · ${esc(o.driver_name)}</span></div><button class="btn ghost" onclick="logout()">Log Out</button></div><div class="dash" style="margin-top:20px"><div class="tabs"><button onclick="tab('trips')">Upcoming Trips</button><button onclick="tab('req')">Requests</button><button onclick="tab('avail')">Availability</button><button onclick="tab('prof')">My Profile</button></div><div id="pane"></div></div></div></section>`;tab('trips')
}
function tab(x){const d=D;if(x==='trips'){const R=d.r.filter(y=>['accepted','confirmed'].includes(y.status));$('#pane').innerHTML='<div class="card"><h3>Upcoming Trips</h3>'+(R.length?R.map(y=>`<div class="trip"><b>${esc(y.service_date)} ${y.artist?'· '+esc(y.artist):''}</b><div class="muted">${esc(y.customer_name)} · ${y.group_size} people · ${esc(y.customer_phone)}</div><div class="muted">Pickup: ${esc(y.pickup_address||y.pickup_area||'TBD')}</div><div>Your transportation price: ${money(y.operator_price_cents)}</div><div class="status">${y.status==='accepted'?'ACCEPTED · CUSTOMER RESERVATION PENDING':'CONFIRMED'}</div></div>`).join(''):'<p class="muted">No accepted trips yet.</p>')+'</div>'}
  if(x==='req'){const R=d.r.filter(y=>y.status==='requested');$('#pane').innerHTML='<div class="card"><h3>New Requests</h3><p class="muted">Accepting unlocks the customer’s separate $59 Red Rocks DD reservation. Your transportation price does not change.</p>'+(R.length?R.map(y=>`<div class="trip"><b>${esc(y.customer_name)} · ${esc(y.service_date)}</b><div class="muted">${y.group_size} people · ${esc(y.customer_phone)} · ${money(y.operator_price_cents)}</div><div class="muted">Pickup: ${esc(y.pickup_address||y.pickup_area||'TBD')}</div><button class="btn red" onclick="respond('${y.id}','accepted')">Accept</button> <button class="btn ghost" onclick="respond('${y.id}','declined')">Decline</button></div>`).join(''):'<p class="muted">No new requests.</p>')+'</div>'}
  if(x==='avail'){const S=new Set(d.a.filter(y=>y.available).map(y=>y.service_date));$('#pane').innerHTML=`<div class="card"><h3>Days You Want to Work</h3><div class="cal">${days().map(q=>`<label class="day"><input type="checkbox" ${S.has(q.v)?'checked':''} onchange="avail('${q.v}',this.checked)"> ${q.l}</label>`)}</div></div>`}
  if(x==='prof'){const o=d.o,v=d.v||{};$('#pane').innerHTML=`<div class="card"><h3>My Profile</h3><div class="fg"><div class="f"><label>Company</label><input id="pc" value="${esc(o.company_name)}"></div><div class="f"><label>Driver</label><input id="pn" value="${esc(o.driver_name)}"></div><div class="f"><label>Phone</label><input id="pt" value="${esc(o.phone)}"></div><div class="f"><label>Your transportation price</label><input type="number" id="pp" value="${o.price_cents/100}"></div><div class="f"><label>Vehicle</label><input id="pv" value="${esc(v.make_model||'')}"></div><div class="f"><label>Capacity</label><input type="number" id="pca" value="${v.capacity||''}"></div></div><div class="f"><label>Driver photo</label><input type="file" id="pdp" accept="image/*">${v.driver_photo_url?`<img class="photo" src="${esc(v.driver_photo_url)}">`:''}</div><div class="f"><label>Vehicle photo</label><input type="file" id="pvp" accept="image/*">${v.vehicle_photo_url?`<img class="photo" src="${esc(v.vehicle_photo_url)}">`:''}</div><div id="pm"></div><button class="btn red" onclick="saveprof()">Save</button></div>`}}
async function respond(id,status){const z=await sb.rpc('respond_red_rocks_dd_request',{p_request_id:id,p_response:status});if(z.error)return alert(z.error.message);dashboard()}
async function avail(d,a){const e=(await sb.from('caddy_availability').upsert({operator_id:D.o.id,service_date:d,available:a},{onConflict:'operator_id,service_date'})).error;if(e)alert(e.message)}
async function saveprof(){const o=D.o,v=D.v||{};let dp=v.driver_photo_url||'',vp=v.vehicle_photo_url||'';try{if($('#pdp').files[0])dp=await file($('#pdp').files[0]);if($('#pvp').files[0])vp=await file($('#pvp').files[0])}catch(e){return msg('#pm',e.message,'bad')};let e=(await sb.from('caddy_operators').update({company_name:$('#pc').value.trim(),driver_name:$('#pn').value.trim(),phone:$('#pt').value.trim(),price_cents:+$('#pp').value*100,updated_at:new Date().toISOString()}).eq('id',o.id)).error;if(e)return msg('#pm',e.message,'bad');const z={operator_id:o.id,make_model:$('#pv').value.trim(),capacity:+$('#pca').value,driver_photo_url:dp,vehicle_photo_url:vp,updated_at:new Date().toISOString()};e=v.id?(await sb.from('caddy_vehicles').update(z).eq('id',v.id)).error:(await sb.from('caddy_vehicles').insert(z)).error;if(e)return msg('#pm',e.message,'bad');msg('#pm','Saved.','good');setTimeout(dashboard,400)}

async function admin(){
  const se=await sess();if(!se)return location.hash='#/login';
  const ok=await sb.rpc('is_red_rocks_dd_admin');if(ok.error||!ok.data)return $('#app').innerHTML='<section class="sec white"><div class="w"><div class="card">Not authorized.</div></div></section>';
  const [ops,req,un]=await Promise.all([sb.rpc('red_rocks_dd_admin_operators'),sb.rpc('red_rocks_dd_admin_requests'),sb.rpc('red_rocks_dd_admin_unmatched')]);
  const O=ops.data||[],R=req.data||[],U=un.data||[];
  $('#app').innerHTML=`<section class="sec white"><div class="w"><div class="row"><div><div class="status">PRIVATE ADMIN</div><h2>RED ROCKS DD ADMIN</h2></div><button class="btn ghost" onclick="logout()">Log Out</button></div><div class="grid"><div class="card"><h3>Operators</h3><div class="price">${O.length}</div><div class="muted">${O.filter(x=>!x.approved).length} pending approval</div></div><div class="card"><h3>Booking Requests</h3><div class="price">${R.length}</div><div class="muted">${R.filter(x=>x.status==='requested').length} waiting on driver</div></div><div class="card"><h3>Unmatched Demand</h3><div class="price">${U.filter(x=>x.status==='open').length}</div><div class="muted">open requests without a listed driver</div></div></div><div class="card" style="margin-top:18px"><h3>Operator Applications</h3>${O.length?O.map(x=>`<div class="trip"><b>${esc(x.company_name)} · ${esc(x.driver_name)}</b><div class="muted">${esc(x.email)} · ${esc(x.phone)} · ${money(x.price_cents)} · License ${esc(x.license_number)}</div><div class="status">${x.approved?'APPROVED':'PENDING'} · ${x.active?'ACTIVE':'INACTIVE'}</div>${!x.approved?`<button class="btn red" onclick="adminSet('${x.id}',true,true)">Approve</button>`:`<button class="btn ghost" onclick="adminSet('${x.id}',true,${!x.active})">${x.active?'Pause':'Activate'}</button>`}</div>`).join(''):'<p class="muted">No operator applications yet.</p>'}</div><div class="card" style="margin-top:18px"><h3>Recent Booking Requests</h3>${R.length?R.slice(0,30).map(x=>`<div class="trip"><b>${esc(x.service_date)} · ${esc(x.customer_name)}</b><div class="muted">${esc(x.customer_email)} · ${esc(x.customer_phone)} · group ${x.group_size}</div><div>${money(x.operator_price_cents)} operator price · <span class="status">${esc(x.status)} / ${esc(x.reservation_fee_status)}</span></div></div>`).join(''):'<p class="muted">No booking requests yet.</p>'}</div><div class="card" style="margin-top:18px"><h3>Unmatched Requests</h3>${U.length?U.slice(0,30).map(x=>`<div class="trip"><b>${esc(x.service_date)} ${x.artist?'· '+esc(x.artist):''}</b><div class="muted">${esc(x.customer_name)} · ${esc(x.customer_email)} · ${esc(x.customer_phone)} · group ${x.group_size}</div><div class="muted">${esc(x.pickup_area||'')} · ${esc(x.notes||'')}</div></div>`).join(''):'<p class="muted">No unmatched requests yet.</p>'}</div></div></section>`
}
async function adminSet(id,approved,active){const z=await sb.rpc('red_rocks_dd_admin_set_operator',{p_operator_id:id,p_approved:approved,p_active:active});if(z.error)return alert(z.error.message);admin()}
async function logout(){await sb.auth.signOut();location.hash='#/'}
function route(){clearInterval(requestPoll);const p=(location.hash||'#/').slice(1).split('?')[0];if(p==='/'||!p)home();else if(p==='/find')find();else if(p==='/company')company();else if(p==='/login')login();else if(p==='/dashboard')dashboard();else if(p==='/request')requestPage();else if(p==='/terms')terms();else if(p==='/privacy')privacy();else if(p==='/admin')admin();else home();scrollTo(0,0)}addEventListener('hashchange',route);route()
